FROM docker.io/nvidia/cuda:11.3.1-cudnn8-runtime-ubuntu20.04

# Copy
COPY . /kcg-ml-sd1p4
WORKDIR /kcg-ml-sd1p4

RUN apt-get update && apt-get install -y python3 python3-pip && apt-get install -y python-is-python3

# local pip cache
RUN pip3 config set global.index-url http://192.168.3.2:5010/index/
RUN pip3 config set global.trusted-host 192.168.3.2

RUN pip3 install -r ./requirements.txt

WORKDIR /kcg-ml-sd1p4
